//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENROLLMENT_V3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string scan {
            get {
                return ((string)(this["scan"]));
            }
            set {
                this["scan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GUA")]
        public string SEDE {
            get {
                return ((string)(this["SEDE"]));
            }
            set {
                this["SEDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SEDE")]
        public string DEVICE_MODE {
            get {
                return ((string)(this["DEVICE_MODE"]));
            }
            set {
                this["DEVICE_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string INTENTOS_ICAO {
            get {
                return ((string)(this["INTENTOS_ICAO"]));
            }
            set {
                this["INTENTOS_ICAO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DRIVE_LETTER {
            get {
                return ((string)(this["DRIVE_LETTER"]));
            }
            set {
                this["DRIVE_LETTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://10.200.0.27/")]
        public string FTP_URL {
            get {
                return ((string)(this["FTP_URL"]));
            }
            set {
                this["FTP_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USB_DEVICE {
            get {
                return ((bool)(this["USB_DEVICE"]));
            }
            set {
                this["USB_DEVICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string PROBATORIOS_GUA {
            get {
                return ((string)(this["PROBATORIOS_GUA"]));
            }
            set {
                this["PROBATORIOS_GUA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string PROBATORIOS_GUA_3_EDAD {
            get {
                return ((string)(this["PROBATORIOS_GUA_3_EDAD"]));
            }
            set {
                this["PROBATORIOS_GUA_3_EDAD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string PROBATORIOS_EXTRANJERO {
            get {
                return ((string)(this["PROBATORIOS_EXTRANJERO"]));
            }
            set {
                this["PROBATORIOS_EXTRANJERO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SUFIJO_ENCRIPTACION {
            get {
                return ((string)(this["SUFIJO_ENCRIPTACION"]));
            }
            set {
                this["SUFIJO_ENCRIPTACION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LOCAL")]
        public string MATCHING_MODE {
            get {
                return ((string)(this["MATCHING_MODE"]));
            }
            set {
                this["MATCHING_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARTICULO_98 {
            get {
                return ((bool)(this["ARTICULO_98"]));
            }
            set {
                this["ARTICULO_98"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/local")]
        public string SERVIDOR_NEURO {
            get {
                return ((string)(this["SERVIDOR_NEURO"]));
            }
            set {
                this["SERVIDOR_NEURO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VALIDAR_HIT {
            get {
                return ((bool)(this["VALIDAR_HIT"]));
            }
            set {
                this["VALIDAR_HIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.1.8")]
        public string IP_SERVICIOS_WEB {
            get {
                return ((string)(this["IP_SERVICIOS_WEB"]));
            }
            set {
                this["IP_SERVICIOS_WEB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FILTRAR_ESCANER_HUELLAS {
            get {
                return ((bool)(this["FILTRAR_ESCANER_HUELLAS"]));
            }
            set {
                this["FILTRAR_ESCANER_HUELLAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VALIDAR_PAGO {
            get {
                return ((bool)(this["VALIDAR_PAGO"]));
            }
            set {
                this["VALIDAR_PAGO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConsultarAsignacionSeEqMe {
            get {
                return ((bool)(this["ConsultarAsignacionSeEqMe"]));
            }
            set {
                this["ConsultarAsignacionSeEqMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VALIDAR_SEQUIPO_SUSUARIO {
            get {
                return ((bool)(this["VALIDAR_SEQUIPO_SUSUARIO"]));
            }
            set {
                this["VALIDAR_SEQUIPO_SUSUARIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CONSULTAR_CITA {
            get {
                return ((bool)(this["CONSULTAR_CITA"]));
            }
            set {
                this["CONSULTAR_CITA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CONFIRMA_CIUDADANO {
            get {
                return ((bool)(this["CONFIRMA_CIUDADANO"]));
            }
            set {
                this["CONFIRMA_CIUDADANO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ESCANER_HUELLAS_LOGIN {
            get {
                return ((string)(this["ESCANER_HUELLAS_LOGIN"]));
            }
            set {
                this["ESCANER_HUELLAS_LOGIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ESCANER_HUELLAS_PASAPORTE {
            get {
                return ((string)(this["ESCANER_HUELLAS_PASAPORTE"]));
            }
            set {
                this["ESCANER_HUELLAS_PASAPORTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FOTO_DPI_FOTO_DOC {
            get {
                return ((bool)(this["FOTO_DPI_FOTO_DOC"]));
            }
            set {
                this["FOTO_DPI_FOTO_DOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XML_PRUEBA {
            get {
                return ((bool)(this["XML_PRUEBA"]));
            }
            set {
                this["XML_PRUEBA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.1.8/citas/datos_personales")]
        public string CITA_BY_ID {
            get {
                return ((string)(this["CITA_BY_ID"]));
            }
            set {
                this["CITA_BY_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.0.55:8080/citas/datos_personales_boleta")]
        public string CITA_BY_PAGO {
            get {
                return ((string)(this["CITA_BY_PAGO"]));
            }
            set {
                this["CITA_BY_PAGO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VALIDAR_SEDE_ENTREGA {
            get {
                return ((bool)(this["VALIDAR_SEDE_ENTREGA"]));
            }
            set {
                this["VALIDAR_SEDE_ENTREGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VALIDAR_FECHA_CITA {
            get {
                return ((bool)(this["VALIDAR_FECHA_CITA"]));
            }
            set {
                this["VALIDAR_FECHA_CITA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.1.8/mostrarFotoPersona")]
        public string FOTO_PERSONA {
            get {
                return ((string)(this["FOTO_PERSONA"]));
            }
            set {
                this["FOTO_PERSONA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CITA_ID {
            get {
                return ((string)(this["CITA_ID"]));
            }
            set {
                this["CITA_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.1.8:8080/entrega_pasaporte")]
        public string INSERTAR_ENTREGA_PASAPORTE {
            get {
                return ((string)(this["INSERTAR_ENTREGA_PASAPORTE"]));
            }
            set {
                this["INSERTAR_ENTREGA_PASAPORTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ENVIAR_FTP {
            get {
                return ((bool)(this["ENVIAR_FTP"]));
            }
            set {
                this["ENVIAR_FTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SERIAL_USB {
            get {
                return ((string)(this["SERIAL_USB"]));
            }
            set {
                this["SERIAL_USB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BIOS {
            get {
                return ((string)(this["BIOS"]));
            }
            set {
                this["BIOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string PUERTO_NEURO {
            get {
                return ((string)(this["PUERTO_NEURO"]));
            }
            set {
                this["PUERTO_NEURO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Biometrics.FaceMatching,Biometrics.FingerMatching,Biometrics.FingerExtraction,Devices.FingerScanners,Images.WSQ,Biometrics.FingerSegmentation,Biometrics.FingerQualityAssessmentBase,Biometrics.FaceExtraction,Biometrics.FaceDetection,Devices.Cameras,Biometrics.FaceSegmentsDetection")]
        public string COMPONENTES_NEURO {
            get {
                return ((string)(this["COMPONENTES_NEURO"]));
            }
            set {
                this["COMPONENTES_NEURO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ESCANEAR_UV {
            get {
                return ((bool)(this["ESCANEAR_UV"]));
            }
            set {
                this["ESCANEAR_UV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.1.8/consultarCasoPasaportexLibreta")]
        public string CONSULTAR_CASO_PASAPORTE {
            get {
                return ((string)(this["CONSULTAR_CASO_PASAPORTE"]));
            }
            set {
                this["CONSULTAR_CASO_PASAPORTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEMP")]
        public string TIPO_CONEXION_ENTREGA {
            get {
                return ((string)(this["TIPO_CONEXION_ENTREGA"]));
            }
            set {
                this["TIPO_CONEXION_ENTREGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SEGMENTAR_ROSTRO {
            get {
                return ((bool)(this["SEGMENTAR_ROSTRO"]));
            }
            set {
                this["SEGMENTAR_ROSTRO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FILTRAR_CAMARA {
            get {
                return ((bool)(this["FILTRAR_CAMARA"]));
            }
            set {
                this["FILTRAR_CAMARA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Integrated Webcam")]
        public string FILTRO_CAMARA {
            get {
                return ((string)(this["FILTRO_CAMARA"]));
            }
            set {
                this["FILTRO_CAMARA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LOCAL")]
        public string TIPO_CONEXION_CONSULTA {
            get {
                return ((string)(this["TIPO_CONEXION_CONSULTA"]));
            }
            set {
                this["TIPO_CONEXION_CONSULTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSTITUTO GUATEMALTECO DE MIGRACION")]
        public string NOMBRE_INSTITUCION {
            get {
                return ((string)(this["NOMBRE_INSTITUCION"]));
            }
            set {
                this["NOMBRE_INSTITUCION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tu pasaporte entregado exitosamente. ")]
        public string MENSAJE_ENTREGA {
            get {
                return ((string)(this["MENSAJE_ENTREGA"]));
            }
            set {
                this["MENSAJE_ENTREGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.1.8/sms/messages_send")]
        public string URL_SEND_TEXT_MESSAGE {
            get {
                return ((string)(this["URL_SEND_TEXT_MESSAGE"]));
            }
            set {
                this["URL_SEND_TEXT_MESSAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ENVIAR_MSG {
            get {
                return ((bool)(this["ENVIAR_MSG"]));
            }
            set {
                this["ENVIAR_MSG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string VALIDAR_ESTADO_POSTIMPRESION {
            get {
                return ((string)(this["VALIDAR_ESTADO_POSTIMPRESION"]));
            }
            set {
                this["VALIDAR_ESTADO_POSTIMPRESION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VALIDAR_USUARIO_GUARDAR {
            get {
                return ((bool)(this["VALIDAR_USUARIO_GUARDAR"]));
            }
            set {
                this["VALIDAR_USUARIO_GUARDAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CONSULTAR_PASAPORTE_GTM {
            get {
                return ((bool)(this["CONSULTAR_PASAPORTE_GTM"]));
            }
            set {
                this["CONSULTAR_PASAPORTE_GTM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELIMINAR_TEMPORALES {
            get {
                return ((bool)(this["ELIMINAR_TEMPORALES"]));
            }
            set {
                this["ELIMINAR_TEMPORALES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IMAGEN_UV_VISIBLE {
            get {
                return ((bool)(this["IMAGEN_UV_VISIBLE"]));
            }
            set {
                this["IMAGEN_UV_VISIBLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^[\\w]+$")]
        public string REGEX_NUMERO_DOCUMENTO {
            get {
                return ((string)(this["REGEX_NUMERO_DOCUMENTO"]));
            }
            set {
                this["REGEX_NUMERO_DOCUMENTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public int ANCHO_PAPEL_PPI {
            get {
                return ((int)(this["ANCHO_PAPEL_PPI"]));
            }
            set {
                this["ANCHO_PAPEL_PPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int ALTO_FUENTE {
            get {
                return ((int)(this["ALTO_FUENTE"]));
            }
            set {
                this["ALTO_FUENTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.0.51:8082/api/movimiento")]
        public string API_CONTROL_ACCESOS {
            get {
                return ((string)(this["API_CONTROL_ACCESOS"]));
            }
            set {
                this["API_CONTROL_ACCESOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PentaScanner4x")]
        public string ESCANER_PASAPORTES {
            get {
                return ((string)(this["ESCANER_PASAPORTES"]));
            }
            set {
                this["ESCANER_PASAPORTES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENROLAR_ROSTRO {
            get {
                return ((bool)(this["ENROLAR_ROSTRO"]));
            }
            set {
                this["ENROLAR_ROSTRO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENROLAR_HUELLAS {
            get {
                return ((bool)(this["ENROLAR_HUELLAS"]));
            }
            set {
                this["ENROLAR_HUELLAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SALIDOS")]
        public string TIPO_MOVIMIENTO {
            get {
                return ((string)(this["TIPO_MOVIMIENTO"]));
            }
            set {
                this["TIPO_MOVIMIENTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IMPRIMIR_TICKET {
            get {
                return ((bool)(this["IMPRIMIR_TICKET"]));
            }
            set {
                this["IMPRIMIR_TICKET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GENERAR_ARCHIVO_JSON {
            get {
                return ((bool)(this["GENERAR_ARCHIVO_JSON"]));
            }
            set {
                this["GENERAR_ARCHIVO_JSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CONSUMIR_API_INS_MOV {
            get {
                return ((bool)(this["CONSUMIR_API_INS_MOV"]));
            }
            set {
                this["CONSUMIR_API_INS_MOV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SEDE_ID {
            get {
                return ((int)(this["SEDE_ID"]));
            }
            set {
                this["SEDE_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/miros/flujo/saveFlujo")]
        public string API_INSERTAR_MOVIMIENTO {
            get {
                return ((string)(this["API_INSERTAR_MOVIMIENTO"]));
            }
            set {
                this["API_INSERTAR_MOVIMIENTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/core/auth/registroBiometrico")]
        public string API_INSERTAR_BIOMETRIA_USUARIO {
            get {
                return ((string)(this["API_INSERTAR_BIOMETRIA_USUARIO"]));
            }
            set {
                this["API_INSERTAR_BIOMETRIA_USUARIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/core/auth/loginDesktop")]
        public string API_LOGIN_USUARIO {
            get {
                return ((string)(this["API_LOGIN_USUARIO"]));
            }
            set {
                this["API_LOGIN_USUARIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/miros/pasaportes/getBiografiaLibreta")]
        public string API_PASAPORTE_BIOGRAFIA {
            get {
                return ((string)(this["API_PASAPORTE_BIOGRAFIA"]));
            }
            set {
                this["API_PASAPORTE_BIOGRAFIA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/miros/pasaportes/getFotoLibreta")]
        public string API_PASAPORTE_FOTO {
            get {
                return ((string)(this["API_PASAPORTE_FOTO"]));
            }
            set {
                this["API_PASAPORTE_FOTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/miros/pasaportes/getHuellasLibreta")]
        public string API_PASAPORTE_HUELLAS {
            get {
                return ((string)(this["API_PASAPORTE_HUELLAS"]));
            }
            set {
                this["API_PASAPORTE_HUELLAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WS")]
        public string TIPO_CONSULTA_PASAPORTE {
            get {
                return ((string)(this["TIPO_CONSULTA_PASAPORTE"]));
            }
            set {
                this["TIPO_CONSULTA_PASAPORTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AFORGE")]
        public string CONTROLADOR_WEBCAM {
            get {
                return ((string)(this["CONTROLADOR_WEBCAM"]));
            }
            set {
                this["CONTROLADOR_WEBCAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/miros/delegacion/getDelegacionById")]
        public string API_SEDE_BY_ID {
            get {
                return ((string)(this["API_SEDE_BY_ID"]));
            }
            set {
                this["API_SEDE_BY_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/miros/delegacion/getEquipoByBios")]
        public string API_EQUIPO_BY_BIOS {
            get {
                return ((string)(this["API_EQUIPO_BY_BIOS"]));
            }
            set {
                this["API_EQUIPO_BY_BIOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/miros/transportedetalle/getTransporteAereo")]
        public string API_GET_VUELOS {
            get {
                return ((string)(this["API_GET_VUELOS"]));
            }
            set {
                this["API_GET_VUELOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://172.16.230.30/externalservices/api/declaracionregional/detailsFromLibreta" +
            "AndBirthday")]
        public string API_DECLARACION_BY_LIBRETA {
            get {
                return ((string)(this["API_DECLARACION_BY_LIBRETA"]));
            }
            set {
                this["API_DECLARACION_BY_LIBRETA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1JUk9TR1RfQ01BSUxBIiwidXNl" +
            "cklEIjoxOSwidGlwb1VzZXIiOjEsImlhdCI6MTcyMTE1NzE4NX0.otfTKEi1ngSwRXBBYkwecSQ-KkNo" +
            "bupYLTox2LRDp9pB09VCFfRE5fzOs5dNOjTqfwfrvj4zvGKt29oAN3lRDA")]
        public string DECLARACION_TKN {
            get {
                return ((string)(this["DECLARACION_TKN"]));
            }
            set {
                this["DECLARACION_TKN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://172.16.80.10/externalservices/api/declaracionregional/details")]
        public string API_DECLARACION_BY_NUMERO {
            get {
                return ((string)(this["API_DECLARACION_BY_NUMERO"]));
            }
            set {
                this["API_DECLARACION_BY_NUMERO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENROLAR_DOCUMENTO {
            get {
                return ((bool)(this["ENROLAR_DOCUMENTO"]));
            }
            set {
                this["ENROLAR_DOCUMENTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/miros/pais/getPais")]
        public string API_GET_PAIS {
            get {
                return ((string)(this["API_GET_PAIS"]));
            }
            set {
                this["API_GET_PAIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CONSULTAR_DJRV {
            get {
                return ((bool)(this["CONSULTAR_DJRV"]));
            }
            set {
                this["CONSULTAR_DJRV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/miros/categoriadocumento/getCategoriaDocumentoById")]
        public string API_GET_TIPO_VISA {
            get {
                return ((string)(this["API_GET_TIPO_VISA"]));
            }
            set {
                this["API_GET_TIPO_VISA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CONSULTAR_ALERTAS {
            get {
                return ((bool)(this["CONSULTAR_ALERTAS"]));
            }
            set {
                this["CONSULTAR_ALERTAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/miros/alerta/getAllAlertas")]
        public string API_ALERTAS {
            get {
                return ((string)(this["API_ALERTAS"]));
            }
            set {
                this["API_ALERTAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CONSULTAR_MOVIMIENTO_SIOM {
            get {
                return ((bool)(this["CONSULTAR_MOVIMIENTO_SIOM"]));
            }
            set {
                this["CONSULTAR_MOVIMIENTO_SIOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000/miros/flujo/getMovimientoSIOM")]
        public string API_MOVIMIENTO_SIOM {
            get {
                return ((string)(this["API_MOVIMIENTO_SIOM"]));
            }
            set {
                this["API_MOVIMIENTO_SIOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VERIFICAR_HUELLA_GTM {
            get {
                return ((bool)(this["VERIFICAR_HUELLA_GTM"]));
            }
            set {
                this["VERIFICAR_HUELLA_GTM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MODO_DIAGNÓSTICO {
            get {
                return ((bool)(this["MODO_DIAGNÓSTICO"]));
            }
            set {
                this["MODO_DIAGNÓSTICO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://consultas_sireci.igm.gob.gt")]
        public string CONSULTAS_RENAP {
            get {
                return ((string)(this["CONSULTAS_RENAP"]));
            }
            set {
                this["CONSULTAS_RENAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ENTREVISTA_TRABAJO_EMPRESA {
            get {
                return ((bool)(this["ENTREVISTA_TRABAJO_EMPRESA"]));
            }
            set {
                this["ENTREVISTA_TRABAJO_EMPRESA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Versión: 2025-04-30-01")]
        public string VERSION {
            get {
                return ((string)(this["VERSION"]));
            }
            set {
                this["VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Valor {
            get {
                return ((string)(this["Valor"]));
            }
            set {
                this["Valor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.8:5000")]
        public string API_REST_MIROS {
            get {
                return ((string)(this["API_REST_MIROS"]));
            }
            set {
                this["API_REST_MIROS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/core/auth/request-reset-footprint")]
        public string API_REQUEST_RESET_TOKEN {
            get {
                return ((string)(this["API_REQUEST_RESET_TOKEN"]));
            }
            set {
                this["API_REQUEST_RESET_TOKEN"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/core/auth/reset-password")]
        public string API_RESET_PASSWORD {
            get {
                return ((string)(this["API_RESET_PASSWORD"]));
            }
            set {
                this["API_RESET_PASSWORD"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/core/auth/validate-reset-token")]
        public string API_VALIDATE_RESET_TOKEN {
            get {
                return ((string)(this["API_VALIDATE_RESET_TOKEN"]));
            }
            set {
                this["API_VALIDATE_RESET_TOKEN"] = value;
            }
        }
    }
}
