//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENROLLMENT_V3.WsBiometricsDGM {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsBiometricsDGM.WsBiometricsDGMSoap")]
    public interface WsBiometricsDGMSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccessLicenseServer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AccessLicenseServer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccessLicenseServer", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AccessLicenseServerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccessLicenses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AccessLicenses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccessLicenses", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AccessLicensesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompararDosHuellasStrBase64IMG_WSQ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CompararDosHuellasStrBase64IMG_WSQ(string strBase64Dedo1, string strBase64Dedo2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompararDosHuellasStrBase64IMG_WSQ", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CompararDosHuellasStrBase64IMG_WSQAsync(string strBase64Dedo1, string strBase64Dedo2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompararDosRostrosStrBase64IMG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CompararDosRostrosStrBase64IMG(string strBase64IMG1, string strBase64IMG2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompararDosRostrosStrBase64IMG", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CompararDosRostrosStrBase64IMGAsync(string strBase64IMG1, string strBase64IMG2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsBiometricsDGMSoapChannel : ENROLLMENT_V3.WsBiometricsDGM.WsBiometricsDGMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsBiometricsDGMSoapClient : System.ServiceModel.ClientBase<ENROLLMENT_V3.WsBiometricsDGM.WsBiometricsDGMSoap>, ENROLLMENT_V3.WsBiometricsDGM.WsBiometricsDGMSoap {
        
        public WsBiometricsDGMSoapClient() {
        }
        
        public WsBiometricsDGMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsBiometricsDGMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsBiometricsDGMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsBiometricsDGMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string AccessLicenseServer() {
            return base.Channel.AccessLicenseServer();
        }
        
        public System.Threading.Tasks.Task<string> AccessLicenseServerAsync() {
            return base.Channel.AccessLicenseServerAsync();
        }
        
        public System.Data.DataSet AccessLicenses() {
            return base.Channel.AccessLicenses();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AccessLicensesAsync() {
            return base.Channel.AccessLicensesAsync();
        }
        
        public System.Data.DataSet CompararDosHuellasStrBase64IMG_WSQ(string strBase64Dedo1, string strBase64Dedo2) {
            return base.Channel.CompararDosHuellasStrBase64IMG_WSQ(strBase64Dedo1, strBase64Dedo2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CompararDosHuellasStrBase64IMG_WSQAsync(string strBase64Dedo1, string strBase64Dedo2) {
            return base.Channel.CompararDosHuellasStrBase64IMG_WSQAsync(strBase64Dedo1, strBase64Dedo2);
        }
        
        public System.Data.DataSet CompararDosRostrosStrBase64IMG(string strBase64IMG1, string strBase64IMG2) {
            return base.Channel.CompararDosRostrosStrBase64IMG(strBase64IMG1, strBase64IMG2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CompararDosRostrosStrBase64IMGAsync(string strBase64IMG1, string strBase64IMG2) {
            return base.Channel.CompararDosRostrosStrBase64IMGAsync(strBase64IMG1, strBase64IMG2);
        }
    }
}
